PhysicsAdvertisements/PhysicsAdvertisements.MVC.Web/Controllers/PartialModulesController.cs
using PhysicsAdvertisements.MVC.Web.ViewModels.PartialModulesViewModels;
using PhysicsAdvertisements.Repository.Repo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhysicsAdvertisements.MVC.Web.Controllers
{
    public class PartialModulesController : Controller
    {
        private ICategoryRepo _categoryRepo;
        private IPhysicsAreasRepo _physicsAreasRepo;


        public PartialModulesController(ICategoryRepo categoryRepo, IPhysicsAreasRepo physicsAreasRepo)
        {
            this._categoryRepo = categoryRepo;
            this._physicsAreasRepo = physicsAreasRepo;
        }

        // GET: PartialModules
        public ActionResult AdvertisementsSearch(AdvertisementsSearchVM data)
        {

            return RedirectToAction("SearchResult", "Advertisement", new { category = data.SelectedCategory, physicsArea = data.SelectedPhysicsArea });
        }


        public List<SelectListItem> GetCategoryControlDataSource()
        {
            List<SelectListItem> data = new List<SelectListItem>();

            var categories = _categoryRepo.Table.Select(x => x.Name).ToList();
           
            foreach(var item in categories)
            {
                data.Add(new SelectListItem() { Text = item });
            }

            return data;

        }


        public List<SelectListItem> GetPhysicsAreaControlDataSource()
        {
            List<SelectListItem> data = new List<SelectListItem>();

            var physicsAreas = _physicsAreasRepo.Table.Select(x => x.Name).ToList();

            foreach (var item in physicsAreas)
            {
                data.Add(new SelectListItem() { Text = item });
            }

            return data;

        }
    }
}

PhysicsAdvertisements/PhysicsAdvertisements.MVC.Web/Views/PartialModules/_AdvertisementsSearch.cshtml
@model  PhysicsAdvertisements.MVC.Web.ViewModels.PartialModulesViewModels.AdvertisementsSearchVM


@using (Html.BeginForm("AdvertisementsSearch", "PartialModules", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    <div class="row advertisements-search">
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <ul>
                <li>Physics areas: </li>
                <li>
                    @Html.DropDownListFor(x => x.SelectedPhysicsArea, Model.PhysicsAreaControlDataSource, new { @class = "combo-box" })
                    @*<asp:DropDownList ID="PhysicsAreaControl"  CssClass="combo-box"> </asp:DropDownList>*@

                </li>
            </ul>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <ul>
                <li>Category: </li>
                <li>
                    @Html.DropDownListFor(x => x.SelectedCategory, Model.CategoryControlDataSource, new { @class = "combo-box" })
                    @*<asp:DropDownList ID="CategoryControl"  CssClass="combo-box"></asp:DropDownList>*@
                    @*@Html.DropDownListFor(x => )*@
                </li>
            </ul>
        </div>
        <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
            <ul>
                <li>
                    <button ID="SearchBtnControl" type="submit" class="btn btn-success SearchBtn">Search</button>
                </li>
            </ul>
        </div>
    </div>
}

PhysicsAdvertisements/PhysicsAdvertisements.MVC.Web/Views/PartialModules/_UserMenu.cshtml
<div class="row menu user-menu">
    <ul>
        <li>
            <a href="/Account/UserData">User data</a>
        </li>
        <li>
            <a href="/Advertisement/Create">Create advertisement</a>
        </li>
        <li>
            <a href="/Advertisement/MyAdvertisements">My advertisements</a>
        </li>
    </ul>
</div>