PhysicsAdvertisements/PhysicsAdvertisements.MVC.Web/Controllers/AdvertisementController.cs
using PhysicsAdvertisements.MVC.Web.ViewModels.AdvertisementViewModels;
using PhysicsAdvertisements.MVC.Web.ViewModels.PartialModulesViewModels;
using PhysicsAdvertisements.Repository.Repo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PhysicsAdvertisements.MVC.Web.Controllers
{
    public class AdvertisementController : Controller
    {

        private ICategoryRepo _categoryRepo;
        private IPhysicsAreasRepo _physicsAreasRepo;
        private IUserRepo _userRepo;
        private IAdvertisementRepo _advertisementRepo;

        public AdvertisementController(ICategoryRepo categoryRepo, IPhysicsAreasRepo physicsAreasRepo, IUserRepo userRepo, IAdvertisementRepo advertisementRepo)
        {
            this._categoryRepo = categoryRepo;
            this._physicsAreasRepo = physicsAreasRepo;
            this._userRepo = userRepo;
            this._advertisementRepo = advertisementRepo;
        }
        

        // GET: Advertisement
        [HttpGet]
        public ActionResult SearchResult(string category, string physicsArea)        
        {
            SearchResultVM dataVM = new SearchResultVM();
            PartialModulesController partialModulesController = new PartialModulesController(_categoryRepo, _physicsAreasRepo);
            dataVM.AdvertisementsSearchPartial.CategoryControlDataSource = partialModulesController.GetCategoryControlDataSource();
            dataVM.AdvertisementsSearchPartial.PhysicsAreaControlDataSource = partialModulesController.GetPhysicsAreaControlDataSource();

            if (category==null|| physicsArea == null)
            {
                dataVM.StatusColor = "Red";
                dataVM.Status = "No advertisements was found";
                return View(dataVM);
            }


            
            var result = _advertisementRepo.Table.Where(x => x.Category.Name == category && x.PhysicsAreas.Name == physicsArea)
                                                .ToList()
                                                .Join(_userRepo.Table,
                                                ad => ad.UserId,
                                                u => u.Id,
                                                (ad, u) => new { ad, u }).Select(s => new AdvertisementVM
                                                {
                                                    //Advertisement
                                                    AddedDate = s.ad.AddedDate,
                                                    AdvertisementTitle = s.ad.Title,
                                                    AdvertisementContent = s.ad.Content,
                                                    AdvertisementCategory = s.ad.Category.Name,
                                                    AdvertisementPhysicsArea = s.ad.PhysicsAreas.Name,
                                                    AdvertisementId = s.ad.Id.ToString(),
                                                    //Exhibitor's(user) data
                                                    UserImageUrl = s.u.Gender == (int)Model.User.GenderEnum.Female ? "../../ecommerce-icon-set-freepik/New/avatar%20girl.png" : "../../ecommerce-icon-set-freepik/PNG/avatar.png",
                                                    Name = s.u.Name,
                                                    Surname = s.u.Surname,
                                                    Email = s.u.Email,
                                                    PhoneNumber = s.u.PhoneNumber,
                                                    Birthday = s.u.Birthday,


                                                })
                                                .OrderByDescending(x => x.AddedDate)
                                                .ToList();

            if (!result.Any())
            {
                dataVM.StatusColor = "Red";
                dataVM.Status = "No advertisements was found";
            }
            else
            {
                dataVM.SearchResultData = result;

                dataVM.StatusColor = "Green";
                dataVM.Status = result.Count + " advertisements was found:";
            }

            return View(dataVM);
        }


        public ActionResult Create()
        {
            if (Session["LoggedUserId"] == null) { return RedirectToAction("Index", "Home"); }

            CreateVM dataVM = new CreateVM();
            dataVM.CategoryControlDataSource = GetCategoryControlDataSource();
            dataVM.PhysicsAreaControlDataSource = GetPhysicsAreaControlDataSource();

            PartialModulesController partialModulesController = new PartialModulesController(_categoryRepo, _physicsAreasRepo);
            dataVM.AdvertisementsSearchPartial.CategoryControlDataSource = partialModulesController.GetCategoryControlDataSource();
            dataVM.AdvertisementsSearchPartial.PhysicsAreaControlDataSource = partialModulesController.GetPhysicsAreaControlDataSource();

            return View(dataVM);
        }

        [HttpPost]
        public ActionResult Create(CreateVM dataVM)
        {
            if (Session["LoggedUserId"] == null) { return RedirectToAction("Index", "Home"); }
            if (!ModelState.IsValid)
            {
                dataVM.CategoryControlDataSource = GetCategoryControlDataSource();
                dataVM.PhysicsAreaControlDataSource = GetPhysicsAreaControlDataSource();

                PartialModulesController partialModulesController = new PartialModulesController(_categoryRepo, _physicsAreasRepo);
                dataVM.AdvertisementsSearchPartial.CategoryControlDataSource = partialModulesController.GetCategoryControlDataSource();
                dataVM.AdvertisementsSearchPartial.PhysicsAreaControlDataSource = partialModulesController.GetPhysicsAreaControlDataSource();

                return View(dataVM);
            }
            else
            {
                try
                {
                    Model.Advertisement advertisement = new Model.Advertisement();
                    advertisement.Content = dataVM.Content;
                    advertisement.Title = dataVM.Title;
                    advertisement.AddedDate = DateTime.Now;

                    advertisement.CategoryId = _categoryRepo.Table.Where(x => x.Name == dataVM.SelectedCategory).Select(x => x.Id).First();
                    advertisement.PhysicsAreasId = _physicsAreasRepo.Table.Where(x => x.Name == dataVM.SelectedPhysicsArea).Select(x => x.Id).First();
                    int loggedUserId = (int)Session["LoggedUserId"];
                    advertisement.UserId = _userRepo.Table.Where(x => x.Id == loggedUserId).Select(x => x.Id).First();

                    _advertisementRepo.Insert(advertisement);
                    _advertisementRepo.Save();

                    dataVM = new CreateVM();
                    ModelState.Clear();
                    dataVM.Status = "Changes saved successfully";

                    dataVM.CategoryControlDataSource = GetCategoryControlDataSource();
                    dataVM.PhysicsAreaControlDataSource = GetPhysicsAreaControlDataSource();

                    PartialModulesController partialModulesController = new PartialModulesController(_categoryRepo, _physicsAreasRepo);
                    dataVM.AdvertisementsSearchPartial.CategoryControlDataSource = partialModulesController.GetCategoryControlDataSource();
                    dataVM.AdvertisementsSearchPartial.PhysicsAreaControlDataSource = partialModulesController.GetPhysicsAreaControlDataSource();


                    return View(dataVM);
                }
                catch (Exception e)
                {
                    //logger implementation
                    return View("Error");
                }
            }

        }
              

        public List<SelectListItem> GetCategoryControlDataSource()
        {
            List<SelectListItem> data = new List<SelectListItem>();

            var categories = _categoryRepo.Table.Select(x => x.Name).ToList();

            foreach (var item in categories)
            {
                data.Add(new SelectListItem() { Text = item });
            }

            return data;

        }


        public List<SelectListItem> GetPhysicsAreaControlDataSource()
        {
            List<SelectListItem> data = new List<SelectListItem>();

            var physicsAreas = _physicsAreasRepo.Table.Select(x => x.Name).ToList();

            foreach (var item in physicsAreas)
            {
                data.Add(new SelectListItem() { Text = item });
            }

            return data;

        }

        public ActionResult DeleteAdvertisement(int? advertisementId)
        {
            if (advertisementId == null)
            {
                return View("Error");
            }

            try
            {
                _advertisementRepo.DeleteById((int)advertisementId);
                _advertisementRepo.Save();             
                return Content("<script language='javascript' type='text/javascript'>alert('Advertisement deleted successfully!'); window.location.replace('MyAdvertisements');</script>");

            }
            catch (Exception e)
            {
                return Content("<script language='javascript' type='text/javascript'>alert('There was an error during deleting the row: "+ e +"'); window.location.replace('MyAdvertisements');</script>");
            }

        }


        public ActionResult MyAdvertisements()
        {
            if (Session["LoggedUserId"] == null) { return RedirectToAction("Index", "Home"); }


            MyAdvertisementsVM dataVM = new MyAdvertisementsVM();
            PartialModulesController partialModulesController = new PartialModulesController(_categoryRepo, _physicsAreasRepo);

PhysicsAdvertisements/PhysicsAdvertisements.MVC.Web/Views/Advertisement/Create.cshtml
@model PhysicsAdvertisements.MVC.Web.ViewModels.AdvertisementViewModels.CreateVM
@{
    ViewBag.Title = "Create advertisement";
}

<link href="~/App_Styles/PartialModules/AdvertisementsSearch_UserPanel.css" rel="stylesheet" />
<link href="../../App_Styles/Advertisement/Create.css" rel="stylesheet" />
<link href="~/App_Styles/PartialModules/UserMenu.css" rel="stylesheet" />

<div class="container">
    <br />
    @Html.Partial("~/Views/PartialModules/_AdvertisementsSearch.cshtml", Model.AdvertisementsSearchPartial)
</div>

<div class="container create">
    <br />
    <div class="col-xs-12 col-sm-8 col-md-8 col-lg-8">
        <h3>Create advertisement</h3>
        <hr />
        @Html.Partial("~/Views/PartialModules/_UserMenu.cshtml")
        @using (Html.BeginForm("Create", "Advertisement", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <div class="row">
                <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                    <label>Title</label>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                    @*<asp:TextBox ID="TitleControl" runat="server" CssClass="form-control" placeholder="Title"></asp:TextBox>*@
                    @Html.TextBoxFor(x => x.Title, new { @class = "form-control", placeholder = "Title" })
                </div>
                <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                    @Html.ValidationMessageFor(x => x.Title)
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                    <label>Physics area</label>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                    @Html.DropDownListFor(x => x.SelectedPhysicsArea, Model.PhysicsAreaControlDataSource, new { @class = "combo-box" })
                </div>
                <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                    @Html.ValidationMessageFor(x => x.SelectedPhysicsArea)
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                    <label>Category</label>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                    @*<asp:DropDownList ID="CategoryControl" runat="server" CssClass="form-control"></asp:DropDownList>*@
                    @Html.DropDownListFor(x => x.SelectedCategory, Model.CategoryControlDataSource, new { @class = "combo-box" })
                </div>
                <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                    @Html.ValidationMessageFor(x => x.SelectedCategory)
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                    <label>Description</label>
                </div>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                    @*<asp:TextBox ID="ContentControl" runat="server" CssClass="form-control" placeholder="Content" TextMode="MultiLine" Style="resize: vertical; height: 300px;"></asp:TextBox>*@
                    @Html.TextAreaFor(x => x.Content, 0, 0, new { @class = "textarea resizer", Style = "resize: vertical; width:100%; height: 300px;", placeholder = "Add description", })
                </div>
                <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                    @Html.ValidationMessageFor(x => x.Content)
                </div>
            </div>

            <div class="row">
                <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                </div>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                    @*<asp:Button ID="SubmitControl" runat="server" Text="Add advertisement" CssClass="btn btn-primary submit" OnClick="SubmitControl_Click" CausesValidation="True" />*@
                    <button ID="SubmitControl" type="submit" class="btn btn-primary submit">Add advertisement</button>
                </div>
            </div>
            <div class="row">
                <div class="col-xs-12 col-sm-3 col-md-3 col-lg-3">
                </div>
                <div class="col-xs-12 col-sm-6 col-md-6 col-lg-6">
                    @*<asp:Label ID="StatusControl" runat="server" Text="" CssClass="status-label"></asp:Label>*@
                    @Html.Label(" ", Model.Status, new { @class = "status-label", Style = "color:green;" })
                </div>
            </div>
        }
    </div>

    <div class="col-xs-12 col-sm-4 col-md-4 col-lg-4">
        <h3>Enjoy!</h3>
        <hr />
        <div style="width: 100%; background-color: #f1efef; height: 540px; border-radius: 5px;">
            <img src="~/App_Images/Account/create_advertisement_object.png" class="img-responsive" alt="create_advertisement_object.png" style=" width: 70%; margin: auto;" />
        </div>
    </div>


</div>

PhysicsAdvertisements/PhysicsAdvertisements.MVC.Web/Views/Advertisement/MyAdvertisements.cshtml
@model PhysicsAdvertisements.MVC.Web.ViewModels.AdvertisementViewModels.MyAdvertisementsVM
@{
    ViewBag.Title = "My advertisements";
}
<link href="~/App_Styles/PartialModules/AdvertisementsSearch_UserPanel.css" rel="stylesheet" />
<link href="~/App_Styles/PartialModules/UserMenu.css" rel="stylesheet" />

<style>
    .user-img {
        height: 100px;
        width: 100px;
    }

    .personal-data, .contact-data {
        list-style-type: none;
        padding: 0px;
    }

    .tbl tbody td {
        border-color: white;
        border-bottom-color: #ded7d7;
    }

    .tbl tr th {
        border-color: white;
        border-bottom-color: #ded7d7;
    }
    .tbl ul{
        list-style-type:none;
        margin:0;
        padding:0;
    }
</style>





<div class="container">
    <br />
    @Html.Partial("~/Views/PartialModules/_AdvertisementsSearch.cshtml", Model.AdvertisementsSearchPartial)
</div>

<div class="container user-data">
    <br />
    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
        <h3>My advertisements</h3>
        <hr />
        @Html.Partial("~/Views/PartialModules/_UserMenu.cshtml")

        <div class="col-xs-12 col-sm-12 col-md-12 col-lg-12">
            @Html.Label(" ", Model.Status, new { @class = "status-label", Style = "color:" + Model.StatusColor + ";" })
        </div>

        <table class="table table-responsive tbl">
            <thead>
                <tr>
                    <td width="120">
                        <label>Added date</label>
                    </td>
                    <td width="120">
                        <label>Exhibitor's image</label>
                    </td>
                    <td>
                        <label>Exhibitor's personal data</label>
                    </td>
                    <td>
                        <label>Physics area</label>
                    </td>
                    <td>
                        <label>Category</label>
                    </td>
                    <td>
                        <label>Title</label>
                    </td>
                    <td>
                        <label>Content</label>
                    </td>
                    <td>
                        <label>Exhibitor's contact data</label>
                    </td>
                    <td>
                        @*Delete buttons*@                      
                    </td>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model.MyAdvertisements)
                {
                    <tr>
                        <td>    @Html.DisplayFor(modelItem => item.AddedDate)   </td>
                        <td>    <img src="@item.UserImageUrl" class="user-img" alt="User image"/>   </td>
                        <td>
                            <ul>
                                @foreach (var personalDataItem in item.FullNameAndAge)
                                {
                                    <li>
                                        @personalDataItem
                                    </li>
                                }
                            </ul>
                        </td>
                        <td>    @Html.DisplayFor(modelItem => item.AdvertisementPhysicsArea)   </td>
                        <td>    @Html.DisplayFor(modelItem => item.AdvertisementCategory)   </td>
                        <td>    @Html.DisplayFor(modelItem => item.AdvertisementTitle)   </td>
                        <td>    @Html.DisplayFor(modelItem => item.AdvertisementContent)   </td>
                        <td>
                            <ul>
                                @foreach (var contactDataItem in item.ContactData)
                                {
                                    <li>
                                        @contactDataItem
                                    </li>
                                }
                            </ul>
                        </td>
                        <td>
                            @Html.ActionLink("Delete", "DeleteAdvertisement", "Advertisement",new { advertisementId = item.AdvertisementId}, new { @class="btn btn-default"})
                        </td>
                    </tr>
                }
            </tbody>
        </table>


        


    </div>
</div>

PhysicsAdvertisements/PhysicsAdvertisements.MVC.Web/Views/Advertisement/SearchResult.cshtml
@{
    ViewBag.Title = "SearchResult";
}

<h2>SearchResult</h2>